### ISSUE TITLE
Rarify mending

### ISSUE THREAD

**Issue by maplepy** [mistrk7/librarians-balance#3]
So if you loot mending you can set the trade with the villager right? Is there a way to block that ? or maybe make it very expensive?

**Comment by mistrk7** [comment]
I don't want to block books outright. Mending is rare and harder to obtain, but because it's technically a Level 1 enchantment its Emerald price can be cheap. Is this something that you would want to see changed?

**Comment by maplepy** [comment]
Yeah what I'd like maybe is to rarify the mending enchant, or make players have to explore more instead of doing big farms to get everything infinitely. I have a server where optimally the goal would be that players have to roam around the whole world to have the best resources. Also if I have the mod installed, there is no config file, is that intended?

**Comment by maplepy** [comment]
Just finding one mending book can effectively make infinite mending books right? Maybe like a finite stock or a longer cooldown? I don't know

**Comment by mistrk7** [comment]
So Mending has already had an increased discovery rate in Ancient Cities, End Cities and some other places. In terms of your last point though, I've made a solution which should tame the issue of 'infinite' mending, books without actually removing that functionality.

First, Mending will always cost either 58 or 64 emeralds. Second, if you trade in a [treasure](https://minecraft.wiki/w/Enchanting#Summary_of_enchantments) enchantment (including Mending) with a villager, the librarian will give you a 'sealed' variant which means that other villagers cannot read from it, but you can still use it on your weapons. This should be fun a server like yours, because whoever earns that treasure enchantment can hold a stockpile for other members and influence how they want it to be shared. 

If you don't like this, you can always disable it fyi. I'm going to release it today. please let me know what you think, and thank you so much for the feedback!

**Comment by mistrk7** [comment]
PS: I've also added the blocking books functionality, so if you really want to prevent books you can.
PPS: here are some screenshots:

Blacklisted books
![image](https://github.com/mistrk7/librarians-balance/assets/66379077/68131cdf-8c7b-4d10-9112-e755309ddb7f)
Sealed books being traded
![image](https://github.com/mistrk7/librarians-balance/assets/66379077/ec7b84f4-3974-49a0-ab98-458d96d2d2ca)
Trying to put a sealed book on a lectern
![image](https://github.com/mistrk7/librarians-balance/assets/66379077/32a85225-2cd5-49b8-bd83-6893af873f20)
