### ISSUE TITLE
Mending still appears in the list and can be traded while trade is still open

### ISSUE THREAD

**Issue by silentSquid** [mistrk7/librarians-balance#6]
Hi there, 

I've come across an issue where Mending still appears in the list of trades and can be traded, but it does go away if you close the trading menu, it gets replaced with Multishot. 
Is there anything I can do to prevent Mending being tradable or is there anything that might conflict with it?

1.20.1 Fabric version 15.7
Tried both Librarian's Balance v1.2 - datapack version and mod version

A few other mods that can be at fault: 
Trade Cycling, Numismatic Overhaul, Villagers Plus

Any idea how I can get it working?
Thank in advance!

**Comment by mistrk7** [comment]
Hi man,

It's normal for mending or a trade greater than three to briefly appear as a trade when opened because that's when the function to replace it executes. 

At that point it's only a visual in the GUI, so when you try to buy that trade it would still result in the replaced trade despite what it's saying.

Thanks for asking :)

**Comment by silentSquid** [comment]
Hey @mistrk7 thanks for the reply!

I got a video of this happening: scrub to 1:40 - is where i find mending trade and trade for a few
https://youtu.be/ESQf7kM_acg?si=bG_4JHczVsK7Sv17&t=99

Datapack is for sure loaded:
![image](https://github.com/mistrk7/librarians-balance/assets/3385529/ebe57c88-6d21-48c1-8b84-6ecdee8d44a5)

And books are still mending after closing the trade window after a few mins
![image](https://github.com/mistrk7/librarians-balance/assets/3385529/477ecfe5-0318-4d6f-b6d6-7137a902fb62)

Any idea why this might be happening?

**Comment by mistrk7** [comment]
Aah I see. The mod you're using (Trade Cycling) allows you to reroll a trade within the GUI, and my datapack doesn't detect that because it only strips out the trades when a villager is right-clicked on or a book is placed on the lectern. 

The only way around this would be to cycle villagers as normal by replacing the lectern or re-opening the GUI every time you cycle a trade using this mod. Unfortunately, I can't directly manipulate what villagers are trading you using a datapack ;-;

**Comment by silentSquid** [comment]
Understood! Thanks for the reply, I suspected as much. Our modpack makes it hard to remove mending 😂 
I'll keep looking for a way, thanks for all your help in figuring this out!

**Comment by mistrk7** [comment]
Hey man, good news. Just wanted to let you know that for 1.21 Mojang are finally making villager enchantments data driven! This means that removing Mending out of their trades, for real, should be much easier in the next update without the need for mods.

**Comment by silentSquid** [comment]
Thanks mistrk7! I actually found another way to deal with it, Villagers Plus mod has the ability to overwrite and replace anyones trades, so I was able to make up my own list of trades for those villagers. So my librarians are now only trading random book related items, and enchants are reserved for the economy part.
Thanks for the help anyways! :)
